# Generated by Django 4.2.28 on 2026-03-27 23:02

import core.fields
import core.utils
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsDashboard",
            fields=[
                (
                    "validity_from",
                    core.fields.DateTimeField(
                        db_column="ValidityFrom", default=datetime.datetime.now
                    ),
                ),
                (
                    "validity_to",
                    core.fields.DateTimeField(
                        blank=True, db_column="ValidityTo", null=True
                    ),
                ),
                (
                    "legacy_id",
                    models.IntegerField(blank=True, db_column="LegacyID", null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("layout_config", models.JSONField(default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="analytics_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_dashboard",
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AnalyticsQuery",
            fields=[
                (
                    "validity_from",
                    core.fields.DateTimeField(
                        db_column="ValidityFrom", default=datetime.datetime.now
                    ),
                ),
                (
                    "validity_to",
                    core.fields.DateTimeField(
                        blank=True, db_column="ValidityTo", null=True
                    ),
                ),
                (
                    "legacy_id",
                    models.IntegerField(blank=True, db_column="LegacyID", null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("group", "Group"),
                            ("beneficiary", "Beneficiary"),
                            ("payment", "Payment"),
                            ("grievance", "Grievance"),
                        ],
                        max_length=50,
                    ),
                ),
                ("query_config", models.JSONField(default=dict)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="analytics_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_query",
                "permissions": [
                    ("view_analytics_query", "Can view analytics queries"),
                    ("execute_analytics_query", "Can execute analytics queries"),
                ],
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AnalyticsWidget",
            fields=[
                (
                    "validity_from",
                    core.fields.DateTimeField(
                        db_column="ValidityFrom", default=datetime.datetime.now
                    ),
                ),
                (
                    "validity_to",
                    core.fields.DateTimeField(
                        blank=True, db_column="ValidityTo", null=True
                    ),
                ),
                (
                    "legacy_id",
                    models.IntegerField(blank=True, db_column="LegacyID", null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("bar_chart", "Bar Chart"),
                            ("line_chart", "Line Chart"),
                            ("pie_chart", "Pie Chart"),
                            ("table", "Table"),
                            ("metric", "Single Metric"),
                            ("map", "Geographic Map"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("config", models.JSONField(default=dict)),
                ("position", models.JSONField(default=dict)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="analytics.analyticsdashboard",
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.analyticsquery",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_widget",
                "ordering": ["dashboard", "id"],
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AnalyticsExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("excel", "Excel"), ("csv", "CSV"), ("pdf", "PDF")],
                        max_length=10,
                    ),
                ),
                ("filters_applied", models.JSONField(default=dict)),
                ("row_count", models.IntegerField()),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.analyticsquery",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_export",
                "ordering": ["-exported_at"],
            },
        ),
    ]
