# Generated by Django 4.2.28 on 2026-09-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsexport",
            name="export_format",
            field=models.CharField(
                choices=[("excel", "Excel"), ("csv", "CSV")], max_length=10
            ),
        ),
    ]
