# Generated by Django 4.2.28 on 2026-09-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_analyticsexport_export_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsquery",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("group", "Group"),
                    ("beneficiary", "Beneficiary"),
                    ("group_beneficiary", "Group beneficiary"),
                    ("payment", "Payment"),
                    ("grievance", "Grievance"),
                ],
                max_length=50,
            ),
        ),
    ]
