# Generated by Django 4.2.28 on 2026-09-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_alter_analyticsquery_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticswidget",
            name="widget_type",
            field=models.CharField(
                choices=[
                    ("bar_chart", "Bar Chart"),
                    ("line_chart", "Line Chart"),
                    ("pie_chart", "Pie Chart"),
                    ("table", "Table"),
                    ("metric", "Single Metric"),
                ],
                max_length=50,
            ),
        ),
    ]
